name: Vercel Deployment

on:

push:

branches:

- main

jobs:

Deploy-Preview:

runs-on: ubuntu-latest

name: Use webapp

steps:

- uses: actions/checkout@v3

- uses: bahmutov/npm-install@v1

- run: npm run lint 

- run: npm run test
